apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
<<<<<<< Updated upstream
  - 172.17.255.1-172.17.255.255 
=======
  - 172.17.255.1-172.17.255.255
>>>>>>> Stashed changes
